# Request
PUT /api/users/12345 HTTP/1.1
Host: example.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 safari/537.36
Content-Type: application/json
Content-Length: 123
Authorization: Bearer
eyJhbGci0iJIUzI1NiIsInR5cCI6IkpXVCJ9..•
Accept: application/json
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Referer: https://example.com/dashboard
Cookie: sessionId=abc123xyz456; lang=en-US


# a blank line here means, everything has been sent
{
    "firstName": "John",
    "LastName": "Doe",
    "email": "john.doe@example.com",
    "age": 30
}




# Response
HTTP/1.1 200 OK
Date: Fri, 20 Sep 2024 12:00:00 GMT
Content-Type: application/json
Content-Length: 123
Cache-Control: no-store
X-Request-ID: abcdef123456
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Set-Cookie: sessionId=abc123xyz456; Path=/; Secure;
HttpOnly
Vary: Accept-Encoding
Connection: keep-alive


# a blank line here means, everything has been sent
"message": "User updated successfully",
"userId": 12345,
"status": "success"


# different type of headers
# 1. User-Agent: Identifies the client software making the request (e.g., browser, mobile app).
# 2. Content-Type: Specifies the media type of the request body (e.g., application/json, text/html).
# 3. Authorization: Contains credentials for authenticating the client with the server (e.g., Bearer token, Basic auth).
# 4. Accept: Indicates the media types that the client can process in the response (e.g., application/json, text/html).
# 5. Cookie: Sends stored cookies from the client to the server for session management or personalization.
# 6. Cache-Control: Directs caching behavior for the request or response (e.g., no-cache, no-store, max-age).
# 7. X-Request-ID: A unique identifier for the request, often used for tracing and debugging purposes.
# 8. Strict-Transport-Security: Instructs the browser to only communicate with the server over HTTPS for a specified period of time, enhancing security.
# 9. Vary: Informs caches that the response may vary based on certain request headers (e.g., Accept-Encoding, User-Agent).
# 10. Connection: Controls whether the network connection remains open after the current transaction (e.g., keep-alive, close).
# 11. Referer: Indicates the URL of the page that made the request, often used for analytics and security purposes.
# 12. Date: Provides the date and time at which the response was generated by the server.


# Represetation Headers
# 1. Content-Length: Specifies the size of the response body in bytes, allowing the client to know how much data to expect.
# 2. Content-Type: Indicates the media type of the response body (e.g., application/json, text/html), helping the client understand how to process the data.


# security headers
# 1. Strict-Transport-Security: Enforces secure (HTTPS) connections to the server, preventing man-in-the-middle attacks
# 2. X-Content-Type-Options: Prevents browsers from interpreting files as a different MIME type, reducing the risk of drive-by downloads.'
# 3. X-Frame-Options: Protects against clickjacking attacks by controlling whether the content can be embedded in an iframe.
# 4. Content-Security-Policy: Helps prevent cross-site scripting (XSS) and other code injection attacks by specifying which sources of content are allowed.
# 5. X-XSS-Protection: Enables the cross-site scripting (XSS) filter built into most modern web browsers, providing an additional layer of protection against XSS attacks.


# HTTP methods
# 1. GET: Retrieves data from the server without modifying it.
# 2. POST: Sends data to the server to create a new resource.
# 3. PUT: Updates an existing resource on the server with the provided data.
# 4. PATCH: Partially updates an existing resource on the server with the provided data.
# 5. DELETE: Removes a resource from the server.


# Idempotent methods
# GET, PUT, DELETE

# Non-idempotent methods
# POST


# CORS (cross-origin resource sharing)
# It allows sever to specify who can access its resources and how they can be accessed. 
# It is a security feature implemented by web browsers to prevent malicious websites from 
# making unauthorized requests to a different domain.


# simple Request
"example.com" -> "api.example.com"
GET /api/products/123 HTTP/1.1
# different Host and Origin headers
Host: api.anotherdomain.com
Origin: https://example.com
Accept: application/json

# server response
HTTP/1.1 200 OK
Content-Type: application/json
# server checks this wheather exists allowed origin in its configuration and 
# if it does, it will include the following header in the response
# Browser will allow the response to be accessed by the requesting origin (example.com)
# wildcard: "*", allow every origin
Access-Control-Allow-Origin: https://example.com

{
    "Product": {
        "id": 123,
        "name": "Example Product",
        "price": 29.99
    }
}


# pre flight Request
# dont have req and resp body
# this method is not GET, POST, HEAD, so browser will send a preflight request to the server to check if the actual request is safe to send.
# includes non simple headers like Content-Type, Authorization, etc.
# inquiring about the server's CORS policy before sending the actual request.
# also about the allowed methods and headers for the actual request.
OPTIONS /api/products/123 HTTP/1.1
Host: api.anotherdomain.com
Origin: https://example.com
Access-Control-Request-Method: PUT
Access-Control-Request-Headers: Content-Type, Authorization


# Respnse to preflight request
HTTP/1.1 204 No Content
Access-Control-Allow-Origin: https://example.com
Access-Control-Allow-Methods: PUT, DELETE
Access-Control-Allow-Headers: Authorization
Access-Control-Max-Age: 86400


# Response codes
Information: 1xx
Success: 2xx
# 200 OK
# 201 Created
# 202 Accepted
# 204 No Content

Redirection: 3xx
# 300 Multiple Choices
# 301 Moved Permanently
# 302 Found
# 303 See Other
# 304 Not Modified - use cached version of the resource

Client Error: 4xx
# 400 Bad Request
# 401 Unauthorized
# 403 Forbidden
# 404 Not Found

Server Error: 5xx
# 500 Internal Server Error
# 502 Bad Gateway
# 503 Service Unavailable
# 504 Gateway Timeout


# HTTP caching
# response contains
# - Cache-Control: Specifies caching directives (e.g., no-cache, no-store, max-age) to control how and 
#   for how long the response can be cached.
# - ETag: Provides a unique identifier for the specific version of the resource, 
#   allowing clients to validate cached responses.


# Content Negotiation
# Accept-Language: Specifies the preferred language(s) for the response, allowing the server to serve content in the appropriate language.
# Accept-Encoding: Indicates the preferred content encoding(s) (e.g., gzip, deflate, br) for the response, 
#   enabling the server to compress the response data accordingly.


# Persistent Connections and Keep-Alive
# Connection: keep-alive: Instructs the server to keep the TCP connection open for multiple requests/responses, 
#   reducing the overhead of establishing new connections for each request.
# Keep-Alive: timeout=5, max=100: Specifies the maximum time (in seconds) the connection should be kept alive and 
#   the maximum number of requests that can be sent over the same connection before it is closed, allowing for
#   efficient reuse of the connection.


# Large data transfer and chunked encoding
# Transfer-Encoding: chunked: Indicates that the response body is being sent in chunks, 
#   allowing the server to start sending data before the entire response is ready, 
#   which is useful for streaming large responses


# TLS, SSL, and HTTPS
# TLS (Transport Layer Security) and SSL (Secure Sockets Layer) are cryptographic protocols
# that provide secure communication over a network. HTTPS (Hypertext Transfer Protocol Secure) is the
# secure version of HTTP that uses TLS/SSL to encrypt data transmitted between a client and a server, 
# ensuring confidentiality, integrity, and authenticity of the data exchanged.